import Link from "next/link";

export default function WalletPage() {
  return <main id="main">
    <div className="page-head"><div><h1>กระเป๋า</h1><p>เงินสด โบนัส ยอดที่พักไว้ และยอดที่ถอนออกได้ แยกให้เห็นชัด พร้อมประวัติรายการแบบภาษาสมาชิก</p></div><div style={{ display: "flex", gap: 8 }}><Link className="button secondary" href="/wallet/deposit">ฝากเงิน</Link><Link className="button primary" href="/wallet/withdraw">ถอนเงิน</Link></div></div>
    <section className="balance-strip"><div><span>เงินสด</span><strong>12,450.00 บาท</strong></div><div><span>โบนัส</span><strong>300.00 บาท</strong></div><div><span>ยอดที่พักไว้</span><strong>120.00 บาท</strong></div><div><span>ถอนออกได้</span><strong>12,330.00 บาท</strong></div></section>
    <section className="grid-2" style={{ marginTop: 18 }}>
      <div className="panel" id="transactions"><div className="panel-title"><h2>ประวัติรายการ</h2><a href="#transactions">ดูทั้งหมด →</a></div><div className="txn-row"><div className="txn-icon">+</div><div><strong>เงินรางวัล · ฮานอยพิเศษ</strong><span>9 ก.ย. 20:18 · SLIP-98211</span></div><div className="txn-amount positive">+1,350.00</div></div><div className="txn-row"><div className="txn-icon">B</div><div><strong>ซื้อหวย · สลากกินแบ่งรัฐบาล</strong><span>10 ก.ย. 11:31 · ORD-20260910-843201</span></div><div className="txn-amount">-120.00</div></div><div className="txn-row"><div className="txn-icon">G</div><div><strong>ใช้โบนัสกับการซื้อหวย</strong><span>10 ก.ย. 11:31 · โปรโมชั่นสมาชิกใหม่</span></div><div className="txn-amount">-30.00</div></div><div className="txn-row"><div className="txn-icon">+</div><div><strong>ฝากเงินสำเร็จ</strong><span>8 ก.ย. 08:42 · DEP-20260908-4112</span></div><div className="txn-amount positive">+1,000.00</div></div></div>
      <aside className="stack"><section className="panel"><div className="panel-title"><h2>ทำรายการ</h2></div><Link className="button lime block" href="/wallet/deposit">+ ฝากเงิน</Link><Link className="button secondary block" href="/wallet/withdraw" style={{ marginTop: 8 }}>ถอนเงิน</Link></section><section className="promo-card"><strong>โบนัสไม่สามารถถอนโดยตรง</strong><p className="muted small" style={{ marginTop: 7 }}>ตรวจยอดเล่น เงื่อนไข และวันหมดอายุของแต่ละสิทธิ์ก่อนใช้งาน</p><Link className="text-link" href="/promotions" style={{ display: "inline-block", marginTop: 10 }}>ดูโปรโมชั่นของฉัน →</Link></section></aside>
    </section>
  </main>;
}
